## Build the perfect model to save Hamid !

### Step 1: Explore the Dataset

In [12]:
import pandas as pd
import numpy as np

df=pd.read_csv("./bricolo_company_test.csv")
test_df=pd.read_csv("./bricolo_company_test.csv")
df= df.drop_duplicates()
df=df.drop("id",axis=1)

In [13]:
for col in df.columns:
    num_missing = df[col].isnull().sum()
    print(col, num_missing)

satisfied 487
evaluation 0
projects 0
work_hours 0
total_time_spent 0
had_accident 0
got_promoted 0
department 0
salary_range 0

In [14]:
# here we wanted to extract all the project names one by one
def extract_project_names(names):
  names = ','.join(names).split(',')

  # Remove leading/trailing whitespaces from each name
  names = [name.strip() for name in names]

  # Get unique names using a set
  unique_names = set(names)
  return  list(unique_names)

unique_names= extract_project_names(df.projects.unique())


# we will create a new column named nproject
df.insert(column="nprojects",loc=6 ,value=np.array([0 for i in range(df.shape[0])]))

for v, name in enumerate(unique_names):
    df.insert(column=name, loc=v + 7, value=np.array([0 for i in range(df.shape[0])]))

    for i, row in enumerate(df.values):
        if row[2].find(name) != -1:
            df.iloc[i, v + 7] = 1
        else:
            df.iloc[i, v + 7] = 0
        df.iloc[i,6]+=df.iloc[i,v+7]

# finnaly we add a new column called the nprojects

### Step 2: Preprocessing phase

In [15]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
one_hot_encoder = preprocessing.OneHotEncoder(sparse=True)


label_mapping = {
    'low': 0,
    'medium': 1,
    'high': 2
}
# we use label encoding for salaray range and department
df["salary_range"] = df["salary_range"].map(label_mapping)

df=df.join(pd.get_dummies(df.department))


df

,satisfied,evaluation,projects,work_hours,total_time_spent,had_accident,nprojects,SecCamp,Salah lFrog,Drug Design,...,IT,RandD,accounting,hr,management,marketing,product_mng,sales,support,technical
0,NaN,0.96,"Penalizing System,Smurfs,AiFest23, SecCamp ,...",226,2,1,5,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0.88,0.80,"Drug Design,Farmy,SecCamp",166,2,0,3,1,0,1,...,1,0,0,0,0,0,0,0,0,0
2,0.69,0.98,"SecCamp ,Smurfs ,WebCamp",214,2,0,3,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0.41,0.47,"SecCamp , AiFest23",154,3,0,2,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0.87,0.76,"Penalizing System,Salah lFrog,WebCamp, AiFest...",254,2,1,4,0,1,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.85,0.81,"Raid Dorms Cook, AiFest23 , Drug Design ,S...",260,3,0,4,0,1,1,...,0,0,0,0,0,0,1,0,0,0
4496,0.21,0.43,"Smurfs ,Drug Design",249,3,0,2,0,0,1,...,0,0,0,0,0,1,0,0,0,0
4497,0.78,0.53,"Raid Dorms Cook,WebCamp, Penalizing System",156,3,0,3,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4498,0.93,0.58,"Farmy,Raid Dorms Cook,Smurfs ,Salah lFrog,Dru...",238,2,0,5,0,1,1,...,0,0,0,0,0,0,0,1,0,0
4499,0.64,0.55,"Penalizing System, SecCamp ,Drug Design",246,2,0,3,1,0,1,...,0,0,0,0,0,1,0,0,0,0

In [16]:
# here we drop the unecessary features and we also label encode the 
df= df.drop("projects",axis=1)
df=df.drop("department",axis=1)

In [17]:
df.salary_range

0       1
1       0
2       0
3       0
4       0
       ..
4495    1
4496    0
4497    0
4498    1
4499    2
Name: salary_range, Length: 4500, dtype: int64

In [18]:
# convert 0.......smth to 0.smth
import re
df["satisfied"] = df["satisfied"].apply(lambda x: float(re.sub(r'\.+(?=\d)', '.', x)) if isinstance(x, str) else x)

df["satisfied"].unique()

array([       nan, 0.88      , 0.69      , 0.41      , 0.87      ,
       0.72      , 0.98      , 0.17      , 0.2       , 0.16      ,
       0.77      , 0.67      , 0.54      , 0.74      , 0.73      ,
       0.49      , 0.92      , 0.76      , 0.43      , 0.11      ,
       0.75      , 0.45      , 0.85      , 0.64      , 0.65      ,
       0.82      , 0.53      , 0.8       , 0.38      , 0.96      ,
       0.83      , 0.1       , 0.94      , 0.12      , 0.63      ,
       0.47      , 0.7       , 0.27      , 0.71      , 0.39      ,
       0.24      , 0.86      , 0.37      , 0.15      , 0.9       ,
       0.81      , 0.79      , 0.55      , 1.        , 0.42      ,
       0.18      , 0.89      , 0.66      , 0.59      , 0.97      ,
       0.95      , 0.84      , 0.33      , 0.99      , 0.48      ,
       0.5       , 0.56      , 0.93      , 0.78      , 0.57      ,
       0.31      , 0.4       , 0.36      , 0.44      , 0.14      ,
       0.09      , 0.52      , 0.32      , 0.34      , 0.23      ,
       0.68      , 0.25      , 0.62      , 0.51      , 0.3       ,
       0.6       , 0.61      , 0.91      , 1.45197726, 0.21      ,
       0.58      , 0.13      , 0.19      , 0.46      , 0.26      ,
       0.22      , 0.35      , 0.29      , 0.28      , 1.37847   ,
       1.34547723, 1.38124268, 1.29101297, 1.31911256, 1.44829321,
       1.30190441, 1.33994175, 1.44245889, 1.25776132, 1.47026086,
       1.335875  , 1.29997178, 1.49583645, 1.33165899, 1.33072796,
       1.4464979 ])

### Step 3: Now, comes the modeling !

In [19]:
df

,satisfied,evaluation,work_hours,total_time_spent,had_accident,nprojects,SecCamp,Salah lFrog,Drug Design,Smurfs,...,IT,RandD,accounting,hr,management,marketing,product_mng,sales,support,technical
0,NaN,0.96,226,2,1,5,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
1,0.88,0.80,166,2,0,3,1,0,1,0,...,1,0,0,0,0,0,0,0,0,0
2,0.69,0.98,214,2,0,3,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,0.41,0.47,154,3,0,2,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0.87,0.76,254,2,1,4,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.85,0.81,260,3,0,4,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
4496,0.21,0.43,249,3,0,2,0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
4497,0.78,0.53,156,3,0,3,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4498,0.93,0.58,238,2,0,5,0,1,1,1,...,0,0,0,0,0,0,0,1,0,0
4499,0.64,0.55,246,2,0,3,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [20]:
# filling out missing data for the satisfied column



def fill_Nan(x):
  if( pd.isnull(x) ):return df.satisfied.mean()
  return x

df.satisfied=df.satisfied.apply(fill_Nan)
for col in df.columns:
    num_missing = df[col].isnull().sum()
    print(col, num_missing)

satisfied 0
evaluation 0
work_hours 0
total_time_spent 0
had_accident 0
nprojects 0
SecCamp 0
Salah lFrog 0
Drug Design 0
Smurfs 0
Penalizing System 0
AiFest23 0
WebCamp 0
Raid Dorms Cook 0
Farmy 0
got_promoted 0
salary_range 0
IT 0
RandD 0
accounting 0
hr 0
management 0
marketing 0
product_mng 0
sales 0
support 0
technical 0

In [21]:
print(df.satisfied.mean())
df.satisfied.unique()

0.6140414854779056

array([0.61404149, 0.88      , 0.69      , 0.41      , 0.87      ,
       0.72      , 0.98      , 0.17      , 0.2       , 0.16      ,
       0.77      , 0.67      , 0.54      , 0.74      , 0.73      ,
       0.49      , 0.92      , 0.76      , 0.43      , 0.11      ,
       0.75      , 0.45      , 0.85      , 0.64      , 0.65      ,
       0.82      , 0.53      , 0.8       , 0.38      , 0.96      ,
       0.83      , 0.1       , 0.94      , 0.12      , 0.63      ,
       0.47      , 0.7       , 0.27      , 0.71      , 0.39      ,
       0.24      , 0.86      , 0.37      , 0.15      , 0.9       ,
       0.81      , 0.79      , 0.55      , 1.        , 0.42      ,
       0.18      , 0.89      , 0.66      , 0.59      , 0.97      ,
       0.95      , 0.84      , 0.33      , 0.99      , 0.48      ,
       0.5       , 0.56      , 0.93      , 0.78      , 0.57      ,
       0.31      , 0.4       , 0.36      , 0.44      , 0.14      ,
       0.09      , 0.52      , 0.32      , 0.34      , 0.23      ,
       0.68      , 0.25      , 0.62      , 0.51      , 0.3       ,
       0.6       , 0.61      , 0.91      , 1.45197726, 0.21      ,
       0.58      , 0.13      , 0.19      , 0.46      , 0.26      ,
       0.22      , 0.35      , 0.29      , 0.28      , 1.37847   ,
       1.34547723, 1.38124268, 1.29101297, 1.31911256, 1.44829321,
       1.30190441, 1.33994175, 1.44245889, 1.25776132, 1.47026086,
       1.335875  , 1.29997178, 1.49583645, 1.33165899, 1.33072796,
       1.4464979 ])

In [11]:

# we extract the standarized values of X from the dataset
df=(df-df.mean())/df.std()

df.to_csv("test.csv",index=False)

In [257]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *
# we split the training data and tesing data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)

In [258]:
# Initialze the estimators
clf1 = RandomForestClassifier(random_state=42)
clf2 = SVC(probability=True, random_state=42)
clf3 = LogisticRegression(random_state=42)
clf4 = DecisionTreeClassifier(random_state=42)
clf5 = KNeighborsClassifier()
clf6 = MultinomialNB()
clf7 = GradientBoostingClassifier(random_state=42)

In [259]:
# Initiaze the hyperparameters for each dictionary
param1 = {}
param1['classifier__n_estimators'] = [10, 50, 100, 250]
param1['classifier__max_depth'] = [5, 10, 20]
param1['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]
param1['classifier'] = [clf1]

param2 = {}
param2['classifier__C'] = [10**-2, 10**-1, 10**0, 10**1, 10**2]
param2['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]
param2['classifier'] = [clf2]

param3 = {}
param3['classifier__C'] = [10**-2, 10**-1, 10**0, 10**1, 10**2]
param3['classifier__penalty'] = ['l2']
param3['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]
param3['classifier'] = [clf3]

param4 = {}
param4['classifier__max_depth'] = [5,10,25,None]
param4['classifier__min_samples_split'] = [2,5,10]
param4['classifier__class_weight'] = [None, {0:1,1:5}, {0:1,1:10}, {0:1,1:25}]
param4['classifier'] = [clf4]

param5 = {}
param5['classifier__n_neighbors'] = [2,5,10,25,50]
param5['classifier'] = [clf5]

param6 = {}
param6['classifier__alpha'] = [10**0, 10**1, 10**2]
param6['classifier'] = [clf6]

param7 = {}
param7['classifier__n_estimators'] = [10, 50, 100, 250]
param7['classifier__max_depth'] = [5, 10, 20]
param7['classifier'] = [clf7]

In [260]:
pipeline = Pipeline([('classifier', clf1)])
params = [param1, param2, param3, param4, param5, param6, param7]

In [ ]:
%%time
# Train the grid search model
gs = GridSearchCV(pipeline, params, cv=3, n_jobs=-1, scoring='roc_auc',verbose=10).fit(X_train, y_train)

In [ ]:
print(gs.best_params_)
gs.best_score_

{'classifier': GradientBoostingClassifier(max_depth=5, random_state=42), 'classifier__max_depth': 5, 'classifier__n_estimators': 100}

0.9859200709286319

In [ ]:
# as we can see the Gradient Boosting Classifier 
gradient_boost_classifier = GradientBoostingClassifier(random_state=42)
param7 = {}
param7['n_estimators'] = [10, 50, 100, 250,300]
param7["learning_rate"]=[0.1,0.01,0.001,0.05]
param7['max_depth'] = [5, 10, 20,25]
param7["loss"]=['log_loss', 'deviance', 'exponential']
grid_search = RandomizedSearchCV(gradient_boost_classifier, param7, cv=5,verbose=10,n_iter=20)

grid_search.fit(X=X,y=Y,)

In [ ]:
# get the best combination of params
grid_search.best_params_

{'n_estimators': 250,
 'max_depth': 10,
 'loss': 'log_loss',
 'learning_rate': 0.1}

In [ ]:
# get the best score
grid_search.best_score_

0.9796170965766011

In [262]:
# now we will retrain the best model with the best parameters
final_classifer=GradientBoostingClassifier(loss="log_loss",learning_rate=0.1,max_depth=10,n_estimators=250)
final_classifer.fit(X,Y)

GradientBoostingClassifier(max_depth=10, n_estimators=250)